<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>AIVectorLauncher</AssemblyName>
    <RootNamespace>AIVectorLauncher</RootNamespace>
    <LangVersion>latest</LangVersion>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>x64</Platforms>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Deterministic>true</Deterministic>
    <ComVisible>true</ComVisible>
    <CorelProgramsDir Condition="'$(CorelProgramsDir)' == ''">$(CORELDRAW_PROGRAMS_DIR)</CorelProgramsDir>
    <CorelProgramsDir Condition="'$(CorelProgramsDir)' == ''">C:\Program Files\Corel\CorelDRAW Graphics Suite 2024\Programs64</CorelProgramsDir>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Corel.Interop.VGCore">
      <HintPath>$(CorelProgramsDir)\Assemblies\Corel.Interop.VGCore.dll</HintPath>
      <EmbedInteropTypes>true</EmbedInteropTypes>
      <Private>false</Private>
    </Reference>
    <Reference Include="RGiesecke.DllExport.Metadata">
      <HintPath>C:\Users\renny\.nuget\packages\unmanagedexports\1.2.7\lib\net\RGiesecke.DllExport.Metadata.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="UnmanagedExports" Version="1.2.7" />
  </ItemGroup>

</Project>
